### ISSUE TITLE
Restriction by browser (Chrome in particular)

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#103]
Could we do something similar to where we [restrict serving our battery to only PCs ](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/views.py#L75) to browsers as well?

In the short term (for the UH2) we'd like to restrict our HITs to only chrome, which seems simple enough to hardcode. In the long term, however, we'd probably want this to be an option for the user...if possible. Mturk unfortunately doesn't have a "browser" qualification.

**Comment by vsoch** [comment]
sure, so only chrome then?

**Comment by IanEisenberg** [comment]
Yep!

**Comment by IanEisenberg** [comment]
This hasn't worked. HIT is currently working on _both_ chrome and firefox. Though not the issue, wouldn't you want:

if request.user_agent.browser != "Chrome":
            return render_to_response("turk/browser_sorry.html")

instead of : 
if request.user_agent.browser == "Chrome":
            return render_to_response("turk/browser_sorry.html")
