### ISSUE TITLE
should have ability to see assignments based on status in battery view

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#119]

**Comment by IanEisenberg** [comment]
@vsoch, the hit management kind of addresses this, but having a non-filtered manager would address this perfectly.

**Comment by vsoch** [comment]
I actually tested adding this view to the single battery view, but the issue is that updating all the hits to render the page takes too long to make it a reasonable page load. This is why I made a separate page.

**Comment by IanEisenberg** [comment]
I like the extra page. I just meant having a battery level "manage" page, that shows approved/progress/etc. workers over all HITs

**Comment by vsoch** [comment]
yes, it would require updating all the hits assignments to make sure the information shown is up to date and accurate, which is too computationally intense to show this for all hits.

**Comment by IanEisenberg** [comment]
Got it.

On Fri, May 6, 2016 at 7:05 PM, Vanessa Sochat <notifications@github.com>
wrote:

> yes, it would require updating all the hits assignments to make sure the
> information shown is up to date and accurate, which is too computationally
> intense to show this for all hits.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/119#issuecomment-217598784>
>



-- 
Best,
Ian
