### ISSUE TITLE
add option for experimenter to specify order of experiments

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#120]
@boomsbloom @cbattista

**Comment by vsoch** [comment]
selection variable added to battery, not yet implemented

![image](https://cloud.githubusercontent.com/assets/814322/14621081/36fedd76-0575-11e6-9d5c-8fb2f6dcabad.png)

**Comment by vsoch** [comment]
added order specification to experiment table - again not yet implemented :)

![image](https://cloud.githubusercontent.com/assets/814322/14621222/265397a4-0576-11e6-8d11-50625970900a.png)

**Comment by vsoch** [comment]
@boomsbloom @cbattista @IanEisenberg this has been implemented and is live, please test!

**Comment by IanEisenberg** [comment]
I don't have time to test now, but will later this week. Nice addition!

**Comment by vsoch** [comment]
np! I think @cbattista and @boomsbloom will be able to, as they needed this functionality asap for the pilot tomorrow.

**Comment by vsoch** [comment]
just got a bug on opbeat - looking into.

**Comment by vsoch** [comment]
The bug was trying to save an empty ("") order, and I added a check for this. How did you submit an empty field via the form?

**Comment by vsoch** [comment]
just got another bug- one sec, fixing!

**Comment by vsoch** [comment]
ok try now.

**Comment by vsoch** [comment]
just fixed another bug.
