### ISSUE TITLE
Custom qualification creates server error

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#139]
New error, not sure what has changed.

Now when I try to add a custom qualification like so:

![qual](https://cloud.githubusercontent.com/assets/9325440/14996524/44a119d8-112f-11e6-9ff1-4cf26a9e4fa0.png)

I get a server error:

![beep](https://cloud.githubusercontent.com/assets/9325440/14996534/4d63aef0-112f-11e6-8d3f-3f5111393106.png)

HITs are created normally if I leave the custom qualification out.

**Comment by vsoch** [comment]
Was this working before? I don't see an error on Opbeat, so tracing this is going to be hard.

**Comment by IanEisenberg** [comment]
This was working before. I don't know what's going on and I'm happy to set aside time to help you in any way I can.

**Comment by vsoch** [comment]
the error on opbeat creating the hit was not related to the qualification type, but rather that you did not specify an assignment duration in hours. Please try again.

**Comment by IanEisenberg** [comment]
Each time I have specified the assignment and HIT duration. I just tried again, same error. Once again I successfully created the HIT after removing the custom qualification.

**Comment by vsoch** [comment]
The value "asdf" is not valid for the parameter QualificationTypeId.

**Comment by IanEisenberg** [comment]
Tried again with an appropriate qual. Still getting an error.

On Thu, May 5, 2016 at 12:10 AM, Vanessa Sochat <notifications@github.com>
wrote:

>   The value "asdf" is not valid for the parameter QualificationTypeId.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/139#issuecomment-217090926>
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
The value "3D0GH0GFNKHIE1VGW9JEICPEQVNL3G" is not valid for the parameter QualificationTypeId.

**Comment by vsoch** [comment]
Do you have sandbox set to false?

**Comment by vsoch** [comment]
What might be relevant is the fact that sandbox and real mturk qualification IDs are different. Regardless, to debug this I would suggest using boto in a python terminal and tweaking the call to create the HIT until your qualificationtypeID is deemed valid. Then we can compare against the server call and adjust as needed.

**Comment by IanEisenberg** [comment]
Nope. Worked now. Did you change anything? I am pretty sure I had an
assignment duration/lifetime duration, appropriate qual, and mturk itself
specified at one point in my testing. Either way, works now!

On Thu, May 5, 2016 at 12:15 AM, Vanessa Sochat <notifications@github.com>
wrote:

> Do you have sandbox set to false?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/139#issuecomment-217091498>
>



-- 
Best,
Ian

**Comment by vsoch** [comment]
The change I made was to require the assignment_duration_in_hours. I didn't see record of the invalid qualificationID until this first error (comparing None to a float to calculate time in hours) was resolved. Glad it was resolved, if you are satisfied feel free to close the issue.
