### ISSUE TITLE
test function to notify workers that have not ever been approved or rejected

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#143]
boto function is [here](http://boto.cloudhackers.com/en/latest/ref/mturk.html#boto.mturk.connection.MTurkConnection.notify_workers) @IanEisenberg will need your assistance to be the worker!

**Comment by IanEisenberg** [comment]
I'm free to test this tomorrow.

On Thu, May 5, 2016 at 8:55 PM, Vanessa Sochat <notifications@github.com>
wrote:

> boto function is here
> <http://boto.cloudhackers.com/en/latest/ref/mturk.html#boto.mturk.connection.MTurkConnection.notify_workers>
> @IanEisenberg <https://github.com/IanEisenberg> will need your assistance
> to be the worker!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/143>
>



-- 
Best,
Ian

**Comment by IanEisenberg** [comment]
boom

**Comment by vsoch** [comment]
yes, success. closing!
