### ISSUE TITLE
Broken Link?

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/expfactory-docker#186]
Going through the `generate#quickstart` I 404'd when I clicked on:

> We’ve [provided an image](https://hub.docker.com/r/quay.io/vanessa/expfactory-builder) that will generate a Dockerfile, and from it you can build your Docker image.

Is this meant to be going [here](https://quay.io/repository/vanessa/expfactory-builder?tab=tags)?

**Comment by vsoch** [comment]
I think I switched to Quay.io, because they don't purge and have better (more secure) tokens for each repository. I think this might be the correct link -> https://quay.io/repository/vanessa/expfactory-builder?tab=tags. If you want to confirm and open a PR that would be great!

**Comment by danieljwilson** [comment]
Okay, done.

**Comment by vsoch** [comment]
Thanks!
