### ISSUE TITLE
Bigger body size for NGINX

### ISSUE THREAD

**Issue by AlvaroAguilera** [expfactory/expfactory-docker#191]
Please consider increasing nginx' default max. body size. 
20MB wasn't enough for us and it takes a while to find out why the results aren't saved to disk.

You can increase this upper bound by adding:

client_max_body_size 200M;

inside the server { } directive in script/nginx.https.conf and nginx.gunicorn.conf.

**Comment by vsoch** [comment]
Did you open this on the wrong repo? Those files are present for expfactory/expfactory - I’m not sure this project here is worked on anymore.

**Comment by vsoch** [comment]
Anyway - I'll get this added for you in the current PR (to be merged soon!) Closing here. Thanks @AlvaroAguilera !
