### ISSUE TITLE
Need to implement backup of data

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#21]
must be encrypted, options could be s3, dropbox... @chrisfilo do you have suggestions for what you do for NeuroVault? Is it encrypted?

**Comment by chrisfilo** [comment]
We use RDS built in backup and regular EBS snapshots. Plus every half a
year everything with DOI goes to Stanford digital library.

**Comment by vsoch** [comment]
cool thanks :)

**Comment by vsoch** [comment]
Another question - I see the RDS instance on AWS, but I don't understand how you are using that for NeuroVault given that the docker-compose specifies a container "db" to be run on the local instance. Did you do something custom to deploy it that is not represented in the NeuroVault repo?

**Comment by vsoch** [comment]
@chrisfilo see above!

**Comment by chrisfilo** [comment]
I'm production we are not using a dockerized postgres instance but directly
connect to RDS. This configured in local_settings.py on the production
server.

**Comment by vsoch** [comment]
ah ok, understood. Did you just manually edit the docker-compose in production to remove db, and then change local_settings.py to specify the aws instance? That seems pretty reasonable. We want to do something like that for experiment factory.

**Comment by chrisfilo** [comment]
Yes for now it's just a manual edit. There must be a cleaner way of doing
this though.

**Comment by vsoch** [comment]
This will be done with amazon rds, figured out and encrypted, closing issue.
