### ISSUE TITLE
Alphabetize expeirments

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#27]
Both in the "add experiment" drop down and in the batteries list of experiments

**Comment by IanEisenberg** [comment]
The add experiment list is in alphabetical order but the experiments in the battery list are in the order you added them. I don't think this is necessarily a problem: #26 is more important.

**Comment by vsoch** [comment]
Looks like the data table has a bug, otherwise you could sort, and this issue would be resolved. Let me look into this.

**Comment by vsoch** [comment]
ok table is fixed, so experiments are sortable by field of choice.
