### ISSUE TITLE
API Development

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#31]
Once we have a user agreement in place, we should discuss specific structure of the API. My thoughts are that we can offer summarized versions of data that are open for all to see. It might be overkill to try and do some kind of API authentication to programatically serve private (not yet public) data. @poldrack and @rwblair we will want to meet to discuss this.

**Comment by rwblair** [comment]
Django rest framework is the most robust and tested of the django api libraries. I don't think authenticating with it should be problematic for api users to see private data. We'll just need to be sure to write plenty of tests to ensure our object/results ownership code is in good shape.

http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/

Of course things are always easier said than done.

**Comment by vsoch** [comment]
I'm on board with Django rest framewor! We just wouldn't want to do the standard of providing N=1 level of results for the "public" version. Should we wait for user agreement stuffs to go through, or just add a basic API and then tweak it when we know details? I'm leaning toward the second...

**Comment by poldrack** [comment]
I think it's fine to start working on the api for authenticated users, and then move to allowing public access once we figure out the legal stuff.

**Comment by vsoch** [comment]
Simple API for results is done.
