### ISSUE TITLE
Indicate which tasks have already been added to battery

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#37]
Right now I have added 56 tasks, and am missing one (I should be at 57). It is now difficult to figure out what I missed.

**Comment by vsoch** [comment]
Working on this now.

**Comment by vsoch** [comment]
Ok, I've separated the functionality of "Add" and "Edit":

![image](https://cloud.githubusercontent.com/assets/814322/13037939/42ad3170-d340-11e5-870e-0ca5a459b2ba.png)

So now you get the equivalent view, but one is to add new experiments:

![image](https://cloud.githubusercontent.com/assets/814322/13037947/8793b96c-d340-11e5-8202-2968cc032937.png)

And one is to edit experiments already in the battery:

![image](https://cloud.githubusercontent.com/assets/814322/13037954/a90e1542-d340-11e5-8452-88169f1cac35.png)
