### ISSUE TITLE
JsPsych init not functioning correctly

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#38]
jspsych display-stage, fullscreen, and presumably other init variables specified in the config file are not actualized. 

It seems that the .click function for #start_experiment_button does not generate a jspsych.init that incorporates config variables. Here is the output:

$("#start_experiment_button").click(function(){
   $("#instructions_modal").hide();
   $("#bootstrap_css").remove()
   jsPsych.init({
timeline: stroop_experiment,
on_data_update: function(data){
console.log(data);
expfactory.recordTrialData(data);
expfactory.djstatus = "UPDATE";
$.ajax({ type: "POST",
contentType: "application/json",
url : "/local/15/",
data : JSON.stringify(expfactory),
dataType: "json",
success: function(data){
console.log(data);
console.log("data update called")
}
});

Compare to the correct output from the same experiment run on expfactory.github.io:
jsPsych.init({
timeline: stroop_experiment,
display_element: "getDisplayElement",
fullscreen: true,
on_trial_finish: function(data){
addID()
},
on_finish: function(data){
jsPsych.data.localSave('stroop_results.csv', 'csv');
expfactory_finished = true;
}
});

**Comment by vsoch** [comment]
Just found the bug!

https://github.com/expfactory/expfactory-python/blob/master/expfactory/vm.py#L185

Will fix asap.

**Comment by vsoch** [comment]
Fixed!

![image](https://cloud.githubusercontent.com/assets/814322/13037651/acfe8d86-d33a-11e5-888d-b3a8a406de2c.png)

**Comment by IanEisenberg** [comment]
Great

On Sun, Feb 14, 2016 at 4:47 PM, Vanessa Sochat <notifications@github.com>
wrote:

> Closed #38 <https://github.com/expfactory/expfactory-docker/issues/38>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/38#event-550114421>
> .
>



-- 
Best,
Ian
