### ISSUE TITLE
Add Experiment failure

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#45]
Three tasks currently are failing to install:
tower of london
psychological_refractory_period_two_choices
psychological_refractory_period_gonogo_choice

**Comment by vsoch** [comment]
I will look at these issues later this week - we figured out the RDS bug and are going to be moving the postgres instance database into RDS.

**Comment by vsoch** [comment]
These experiments are failing because their names are not unique. If you have experiments with the same "name" variable, how is the user supposed to know how they are different?

**Comment by vsoch** [comment]
These will install when the name is made unique, I'm closing this issue.

**Comment by IanEisenberg** [comment]
Got it. Thanks!

On Tuesday, March 8, 2016, Vanessa Sochat <notifications@github.com> wrote:

> These will install when the name is made unique, I'm closing this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/45#issuecomment-193901003>
> .
>


-- 
Best,
Ian

**Comment by vsoch** [comment]
FYI - I have a PR running now with fixed names.
