### ISSUE TITLE
errors with making hits

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#50]
I received a number of errors when creating hits. First, when submitting a "New HIT" I get this error:

![new hit error](https://cloud.githubusercontent.com/assets/9325440/13654604/234767e8-e60e-11e5-8c7b-204d80cce3d7.png)

Regardless of the error, a HIT seemed to be created. However, I got errors when I tried to expire or delete the HIT:

Expire:
![expire_hit](https://cloud.githubusercontent.com/assets/9325440/13654610/34417322-e60e-11e5-93bc-1d7de4268262.png)

Delete:
![delete_hit](https://cloud.githubusercontent.com/assets/9325440/13654620/3b4298c2-e60e-11e5-8ddc-aaa69ca36c83.png)

**Comment by vsoch** [comment]
This is an error with the credentials Dartmouth provided you, if you read the message it tells you what is needed is to register the account on mturk.

**Comment by IanEisenberg** [comment]
Yep, I see it now. The text is foreboding, but it is clear if I look :) Fixed that, thanks!
