### ISSUE TITLE
Issues creating HIT

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#51]
When I create a HIT, though only one entry shows up in expfactory.org, two HITs are created on Mturk.

If I press "Expire HIT", it expires one of those two HITs but not the other. If I press "Delete HIT" it only expires the HIT, doesn't delete.

When I look at the HIT, no ad is shown. I can't start the HIT. I've included the following in the "Ad" box:

<p>Thank you for your interest in our experiment!</p>

<p>This is a large experiment with many different tasks for you to do. The HIT should last around 10 hours and will pay $60 plus performance bonuses linked with some of the tasks.</p>P

<p>Most of these tasks require that you press keys and sometimes we'll ask you to respond quickly. It is very important that you follow all the instructions and don’t mindlessly press the keys to finish the HIT more quickly! Not only will this hurt our research, but all of the tasks are designed to take around the same amount of time no matter how quickly you respond. The tasks will be more interesting to you and useful for us if you follow the instructions and try your best on all of the tasks.</p>

<p>If you accept the HIT you will see a start button. After you press start you will be shown a waiver of consent to read over followed by a more detailed description of this HIT.</p>

**Comment by vsoch** [comment]
> When I create a HIT, though only one entry shows up in expfactory.org, two HITs are created on Mturk.

> If I press "Expire HIT", it expires one of those two HITs but not the other. If I press "Delete HIT" it only expires the HIT, doesn't delete.

I haven't seen this behavior, will look into it later this week.

> When I look at the HIT, no ad is shown. I can't start the HIT. I've included the following in the "Ad" box:

It's always been like that, to the best of my understanding. I've only tried this in the sandbox, and to start a preview hit, I usually did view source to get the iframe url, and then went there.

**Comment by IanEisenberg** [comment]
Ah, mturk is throwing this error at preview:

Refused to display 'https://expfactory.org/turk/5?assignmentId=ASSIGNMENT_ID_NOT_AVAILABLE&hitId=3JHB4BPSFK8MXDE1EBB3RW4RV6S9QZ' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

maybe that's helpful? I'm not sure exactly what you mean about the preview. The ad should display, even in sandbox.

**Comment by vsoch** [comment]
That looks like a HIT you deleted

**Comment by vsoch** [comment]
I can confirm that the ad was displaying before, given our mturk credentials, on sandbox.

**Comment by IanEisenberg** [comment]
I did delete the HIT...but this was before I deleted it. I'll make a new HIT and just leave it there for you to peruse in your own time.

**Comment by vsoch** [comment]
I'll probably need the login stuffs then. Thanks.

**Comment by IanEisenberg** [comment]
Preview is resolved. Double HIT is all that's left.

**Comment by vsoch** [comment]
:)

![image](https://cloud.githubusercontent.com/assets/814322/13656559/b95de91a-e61c-11e5-8d07-903dd5019def.png)

**Comment by vsoch** [comment]
ok confirmed the bug when using "New Hit," will debug later.

**Comment by vsoch** [comment]
You deleted your comment:

      Even though duplicate HITs show up as a requester, as a worker I am only seeing one. Not sure what that's about.

If this is the case, then it's not really important to try and debug amazon for why two are showing up in the sandbox for requester.

**Comment by IanEisenberg** [comment]
I deleted that comment because I was wrong - as a worker it showed "2 such HITs available". So the bug is apparent both as a worker and requester.
