### ISSUE TITLE
Experiment not starting/can't leave preview window

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#53]
When I click "Start Experiment" at the end of the preview phase, the experiment isn't starting. I'm not sure what, if anything, is supposed to happen. Look like this:

![empty_preview](https://cloud.githubusercontent.com/assets/9325440/13656662/9aaebad4-e61d-11e5-895e-520fc7dd9eff.png)

**Comment by vsoch** [comment]
You told me to do this. You specified that they should not see anything beyond the instructions.

**Comment by IanEisenberg** [comment]
Yes, that is definitely correct! What I mean is nothing else is starting. Shouldn't another tab open up or something with the full experiment?

Combining with #52, the ideal behavior would be:
(In preview window):
Display (if defined) Ad, Consent, Instructions
The last page should end with "Accept HIT" instead of "Begin Experiments"

Once you accept the HIT, a new window opens at the Consent (no Ad). Now when you get to the end of those intro pages it shows "Begin Experiment" like normal.

That behavior would be great, but the current behavior is fine, except for the fact that a window where I can run experiments doesn't seem to open.

**Comment by vsoch** [comment]
The full experiment, or any inkling to see the experiment, is only available when the requester accepts the hit. I'm not sure how that works in sandbox.

The Ad is not going to be decoupled from the experiment, it's part of the consent, etc.

**Comment by vsoch** [comment]
The only thing shown in the Sandbox is a preview, which is a different link than what is generated for the actual experiment. Show me the link you are using from the preview, and I'll tell you how to change it to test what will be linked to from an actual click.

**Comment by IanEisenberg** [comment]
I'm going to close this issue, I see my problem.
