### ISSUE TITLE
Important: Set qualifications requirements for workers for HITs

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#68]
We need to be able to set requirements on workers who complete our HITs.

In a GUI it would be like so:
[qualifications in GUI form](http://www.blindfiveyearold.com/mechanical-turk-tips)

Through the api, you can set qualifications based on numbers
[qualifications API](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QualificationRequirementDataStructureArticle.html#CustomQualificationsandSystemQualifications)

For instance, in the above URL you can see two worker variables of interest: NumberHITsApproved and PercentAssignmentsApproved. We would want to require (for instance) that NumberHITsApproved is greater than 5000 and PercetAssignmentsApproved is greater than 98%.

There is also "Worker_Locale". We want to ensure that workers are in the US. "Worker_Adult", we want to ensure that that is true.

These should be defined on a HIT-by-HIT-basis. That may get annoying, so another option is to set "default" qualifications in the battery that can be overwritten in each individual HIT (definitely easier).

**Comment by vsoch** [comment]
![image](https://cloud.githubusercontent.com/assets/814322/13821816/66720620-eb60-11e5-809c-107507c0d84f.png)

**Comment by vsoch** [comment]
[Here are the functions for qualifications with boto](http://boto.cloudhackers.com/en/latest/ref/mturk.html) - it looks like "create_hit" takes a qualification object, but it's not clear to me how/where that gets set up, because "create_qualification_type" seems to be a thing that is deployed on MTurk? Are the proper steps:

- create qualification type (this is a test / survey a worker takes on mturk?)
- link qualification test to hit
- create HIT

then

- worker finds hit, is directed to "qualification type" object
- if passes, allowed to take HIT

**Comment by IanEisenberg** [comment]
I believe "create_qualification_type" allows you to create custom qualifications. For instance, you can assign some workers who do you studies the type "star_worker", or those that complete a certain subset "group1_workers", which you can then use similarly to other "preset" worker attributes like NumberHITSApproved.

I think the qualification object is related to the "QualificationRequirement" object [here](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITOperation.html):

*************************************************
**QualificationRequirement**
A condition that a Worker's Qualifications must meet before the Worker is allowed to accept and complete the HIT.

Type: a QualificationRequirement data structure.

Default: None

Constraints: there can be no more than 10 QualificationRequirement data structures for each HIT.
****************************************************

You can add qualification objects of [this form](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QualificationRequirementDataStructureArticle.html). So you could say something like:
QualificatioNTypeID: "NumberHITSApproved",
Comparator: GreaterThan
IntegerValue: 5000

**Comment by vsoch** [comment]
The Amazon API is a general API that isn't necessarily all mapped onto the wrapper we are using, which is called [boto](http://boto.cloudhackers.com/en/latest/ref/mturk.html) for python, so references to functions should be from there.

**Comment by IanEisenberg** [comment]
Okay. So there is this function:

create_hit(hit_type=None, question=None, hit_layout=None, lifetime=datetime.timedelta(7), max_assignments=1, title=None, description=None, keywords=None, reward=None, duration=datetime.timedelta(7), approval_delay=None, annotation=None, questions=None, qualifications=None, layout_params=None, response_groups=None)
Creates a new HIT. Returns a ResultSet See: http://docs.amazonwebservices.com/AWSMechTurk/2012-03-25/AWSMturkAPI/ApiReference_CreateHITOperation.html

which has that qualifications parameter. Not sure exactly what that takes, but I'd imagine a boto.mturk.qualification.

boto.mturk.qualification has a number of [preset types](http://boto.cloudhackers.com/en/latest/ref/mturk.html)

The ones we want are already there, so I believe we can just pass a boto.qualification object to "create_hit" where the boto.qualification has parameters/variables (not sure the word) like...

boto.mturk.qualiifcation.AdultRequirement(EqualTo, 1),
boto.mturk.qualiifcation.PercentAssignmentsApprovedRequirement(GreaterThan, 98)
etc...

The values for those qualifications should be available to the user, but we can hard code them now if that's easier. There is also the issue of "custom" qualifications, which can be created using create_qualification_type (I believe). We don't have to worry about that right now, but probably want to give users a qualification type related to the battery a worker completes so that we can potentially restrict people from accepting HITs related to batteries they have completed.

**Comment by vsoch** [comment]
added qualifications to HIT object:

![image](https://cloud.githubusercontent.com/assets/814322/13822986/052f7fd2-eb65-11e5-9495-b6f1172e49d8.png)

Need to test generation of qualifications, and passing to hit next.

**Comment by vsoch** [comment]
Adult field is also added, I generated a HIT (search for SelfConcept) with qualifications, please test!

![image](https://cloud.githubusercontent.com/assets/814322/13824477/725ac7f0-eb6b-11e5-952d-a4af189e8649.png)
