### ISSUE TITLE
Issues with submission/approval

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#70]
On sandbox everything seems to be working well.

On real mturk submission automatic approval is not working. Submission is working with a caveat: if someone has already completed some work for a battery, and accept a second HIT for the same battery (which we shouldn't allow really) submission doesn't work. If someone has already completed TaskA/TaskB, and accepts a HIT they are told "no experiments are available to you", but no submission. Of course, we don't want someone to be able to select two separate HITs for the same battery (we will probably have to use qualifications to prevent this), but yeah - weird behavior seems to be going on.

On the first acceptance of a HIT when a worker has not done anything for a battery it seems that submission is working fine.

**Comment by vsoch** [comment]
The design is so that a worker cannot complete multiple hits from the same battery. A battery is a collection of experiments - the same experiments - and so if you want different sets of experiments, you create a different battery.
