### ISSUE TITLE
battery needs option to have custom qualification

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#76]
For @IanEisenberg

**Comment by IanEisenberg** [comment]
Works great for our current purposes. In principle, some people may want to be able to use a custom qualification of a certain value. For instance, they may have people do a test and give them all qualifications "my_test_performance" equal to their test performance. Then in another HIT they may only want people who did better than 70/100 on that test. 

Basically, we probably want the option to change the comparator from "EqualTo" and specify the value. The default comparator/value should be "EqualTo" and "1", as they are now.
