### ISSUE TITLE
Delete button and problem clicking on HITs

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#79]
Clicking on HITs isn't working correctly. I will click on the top most HIT and the one underneath is clicked.
You can't see, but in the screenshot below my mouse was over the top "Behavioral Study of Cognitive Function"
![screenshot from 2016-03-22 15 16 52](https://cloud.githubusercontent.com/assets/9325440/13969623/40cd92a0-f041-11e5-8a9b-17e735816904.png)

The Delete button also doesn't delete - only expires. Should probably be Boto's dispose_hit.

**Comment by vsoch** [comment]
Fixed please test.

**Comment by IanEisenberg** [comment]
If a HIT is already expired, delete HIT deletes it. This may be unavoidable functionality (not sure if you can straight force a HIT to be deleted), but is confusing. If delete hit can't actually just force a delete we probably want the button unavailable unless the HIT is expired.
