### ISSUE TITLE
Pilot Preparation

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#8]
Now that we have fix #4 and have certificates for https, the server must be run in production mode in order to allow https to work with Django. We have two options here:

- deploy in production outside of Docker (faster and easier, as we are currently developing outside of it, but this means we will still need to find the correct nginx container image to somehow connect to /deploy the same certificates).
- deploy with Docker (harder as will need to figure out the above, but then it means that the piliot is more production ready).

When we decide on the above we can 1) deploy in production 2) pilot within lab to collect results and feedback, 3) meet with Russ and Ian to decide on new model with "forms" and make changes, and 4) pilot with larger group. Bonus / reject is in place #6 but we will still need some interface to manage the hits (and pending credits, etc) along with some kind of results interface. Right now all that can be done is download of results to tsv, which isn't so bad as this is the minimum requirements for this to work.

**Comment by poldrack** [comment]
what’s the benefit of deploying with docker?

**Comment by vsoch** [comment]
It's a lot more seamless of an application when it needs to be setup on a new server - the entire infrastructure is a already "[Dockerized](https://github.com/expfactory/expfactory-docker/blob/master/docker-compose.yml)" and would just need to be updated with a container to support the SSL. I've been developing on the current server outside of docker with:

      python manage.py runserver 0.0.0.0:8000

only because it's easier to make changes / debug than having to rebuild / restart the containers.
