### ISSUE TITLE
Workers not completing HITs

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#80]
This is more pertinent to the UH2 project (or other large HITs) rather than expfactory as a whole.

Right now if a worker doesn't not finish all tasks (and thus does not trigger the celery task to submit/approve), the HIT will eventually expire. This could happen if the worker stops doing tasks, or is prevented from doing tasks due to our blacklist.

When a worker's HIT expires it is not submitted to the requester. The requester has no way of paying for the work. I believe we talked about a HIT being submitted automatically near the deadline? I can't remember if we said "right before the deadline" (which may be necessary) or right after. We would want this. In both of these cases (or any case where the work isn't completed) we want the work to be submitted and NOT approved, so that payment can proceed through the bonus structure. Eventually this bonus payment will be automatically handled.

**Comment by IanEisenberg** [comment]
@vsoch, how does this currently work? If the HIT gives the worker 2 weeks, what happens at the end of 2 weeks if all the experiments aren't completed/credited?

**Comment by vsoch** [comment]
The job runs are they are given credit.

see [here](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/tasks.py#L16)

If you want something different to happen, that's the function you want to change.
