### ISSUE TITLE
batches in progress not showing up

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#85]
@tnsgmddb brought up this error. Normally when HITs are accepted (before they are submitted) "batches in progress" should progress (see screenshot below). Right now, even though HITs are accepted and being worked on, the batches in progress does not increase. After some workers finish I'll see if "Batches ready for review" increase.

![screenshot from 2016-03-24 10 56 16](https://cloud.githubusercontent.com/assets/9325440/14026224/1d1e5244-f1af-11e5-9051-569c0adf814d.png)

**Comment by IanEisenberg** [comment]
On second look, I'm not sure if this is a problem on our end. I'll update this issue after I figure that out.

**Comment by tnsgmddb** [comment]
Thank you for posting this issue. As a follow-up on our phone meeting yesterday, here is an example of the screenshot for progress bars that we suppose to see on Mturk. Even if a HIT was not taken by anyone, the progress bar should be still up on the page.  

![progressbarsmturk](https://cloud.githubusercontent.com/assets/16784562/14027219/ecf5fb12-f1cc-11e5-9444-d38a8dfdd937.png)

**Comment by IanEisenberg** [comment]
What is the difference between batches and HITs? I think that may be why we aren't seeing anything. We are publishing individual HITs and I have a feeling batches are groups of HITs, or something like that.

**Comment by vsoch** [comment]
It's logical there is no progress bar - we are serving an external hit and there is currently no communication with Amazon about the HIT until it is submit.

**Comment by vsoch** [comment]
For the batch progress that reflects submission - how could we assess this if no one has submit yet?

**Comment by tnsgmddb** [comment]
I am pasting Vanessa's email from before. 
"We are serving the HIT from an external URL, and we don't send results back to AWS, so you won't see progress until they submit and the hits are approved."


this seems to address Ian's question I believe?

**Comment by IanEisenberg** [comment]
We have those random "answer a question" hits I mentioned a bit ago. They
have been completed and were pending review while the batches pending
review remained 0. That's why I think batches and hits are not the same.

On Thursday, March 24, 2016, Vanessa Sochat <notifications@github.com>
wrote:

> For the batch progress that reflects submission - how could we assess this
> if no one has submit yet?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/85#issuecomment-200962764>
>


-- 
Best,
Ian

**Comment by tnsgmddb** [comment]
@IanEisenberg , that's correct. A batch is a group of HITs. 

As an example statement, 
Requesters make a micro-batch that has only 9 slots. This group of 9 slots (9 HITs) is a batch.  

When a batch is created on Mturk internally, I should see a progress bar immediately for each batch even if no one has started or submitted the HIT.
But according to @vsoch ,  because you guys are running HIT's externally, I understand that I will not see a progress bar for a batch unless the batch is all complete, So if you assigned 2 slots for one batch, I believe those 2 HITs should be all submitted by two workers. Then I will be able to see a progress bar on Mturk internally.

**Comment by IanEisenberg** [comment]
If a progress bar is just "how many assignments are accepted out of total assignments", expfactory should not interact with it. Mturk should know how many assignments are currently "in progress" based on which workers currently have accepted the HIT. Progress _within_ the HIT is something else, and not related to this "batch" progress.

Again, we have HITs in this account that have nothing to do with experimentfactory, and the batch counters are not showing them. Not sure what's going on, but I don't think it's related to experiment factory.

**Comment by IanEisenberg** [comment]
I don't think this is an expfactory issue. Closing.
