### ISSUE TITLE
Data should save the current version of the experiment 

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#93]
Experiment Factory experiments can be updated, but the version is not reflected anywhere in the data. Considering they are updated from github, could we just attach the commit to each dataset?

**Comment by vsoch** [comment]
I'm not sure what you mean about version, the experiments do not have versions.

**Comment by IanEisenberg** [comment]
They kind of do...

Let's call the stroop task at this moment stroop1. If I find out there is a problem with the stroop task and want to update it I'd update expfactory-experiments and manually update the experiment on expfactory.org. It's still called stroop, but it's really stroop2. But the data generated for both just show 'stroop'. I'd want to be able to go back and tell the difference between the two datasets. In principle expfactory shouldn't change, but it definitely will (task bugs will be found) and we should tag the data in some way to reflect that. I mentioned commits because the last commit for the directory expfactory-experiments/stroop should let me know if there has been a change.

Does that make sense?

**Comment by vsoch** [comment]
Yes, I know what a version is. This is a larger problem that needs to be addressed properly at some point, I'm not convinced relying on github commits is the optimal solution.

**Comment by IanEisenberg** [comment]
Sure, commits may not be the right way to do this, but (regardless of the larger problem), the smaller problem of needing to know which task each person did is an immediate problem. During our pilot tasks will be updated frequently and somewhat arbitrarily (if a problem is found with a task we will want to update it ASAP for other pilot subjects) and we need to know how which people took which tasks. I have no opinion or perspective on the larger versioning discussion for expfactory.

**Comment by vsoch** [comment]
It's the same issue, so if the problem exists and this is imminent, a solution should be discussed now. I don't want to implement something that will be replaced by something else. Maybe talk to Russ/Chris, let me know what you guys decide.

**Comment by IanEisenberg** [comment]
Will do!

**Comment by vsoch** [comment]
Great! :)
