### ISSUE TITLE
test deployment of games

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-docker#96]
refactor serving functions

**Comment by vsoch** [comment]
https://expfactory.org/batteries/4/f96ecc05-ed9b-4197-9cba-f288342dafe1/accept

**Comment by vsoch** [comment]
@boomsbloom going to need your help debugging this - good news is we are up and running, and the sync is triggering!

Right now there is a server error, and it's because we aren't parsing the expfactory.taskdata correctly. Could you look at the link above and tell me what variable in expfactory to look at to see the data? Let me know if you need to see anything else - once we get the local sync working, it's pretty trivial to edit the mturk deployment template to be able to serve the game too!

**Comment by boomsbloom** [comment]
so in saver.js I call expfactory.recordTrialData(data) where data is a js dict of the experiment variables. That calls addTrialData(data). So trialdata going into addTrialData is equal to the task data. After all that happens, in saver.js expfactor is turned into a json and posted to whatever the url is. Does that help? It's totally possible that I screwed the expfactory thing up

**Comment by vsoch** [comment]
Thanks this is very helpful! Tomorrow I will be in Mountain View for the day and may not have huge amounts of time to work, but I feel pretty confident that this will be figured out in the next few days. What I can do is look into the Game/Run variables specifically, and save data from the response on the server, and those two things should give me a good idea of how to code the server side stuffs. Will keep you updated!

**Comment by boomsbloom** [comment]
sounds good! let me know if you need anything else

**Comment by vsoch** [comment]
game data is saving for local sync!

![image](https://cloud.githubusercontent.com/assets/814322/14188088/1f467c72-f73b-11e5-9f17-a305ee7092c7.png)

**Comment by vsoch** [comment]
@boomsbloom - we need to have some kind of "onFinish" function that I can control to give the user options to continue to the next experiment, redo, etc. What are your thoughts?

**Comment by vsoch** [comment]
no rush on this - I'm leaving to bike to Mountain View asap! Here is the current template that renders the experiment:

[serve_battery.html](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/experiments/templates/games/serve_battery.html) is the base template that the static files (css,js) get rendered into
[saver_local.html](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/experiments/templates/games/saver_local.html) is your (slightly) modified saver.js, we could maybe have an equivalent function here that triggers on completion of the game?
